### ISSUE TITLE
Version 2019.1 Breaking Changes

### ISSUE THREAD

**Issue by nvindice** [aimeos/aimeos-core#137]
Hi @aimeos team,

I just updated to 2019.1 and it kind of broke everything. Now I'm trying to fix all the "bugs" one by one, which is mildly annoying. I strongly suggest to try to avoid breaking changes and use some kind of "deprecation warnings" (e.g. in wrappers around the new function) for a few versions before ultimately removing or renaming functions. The way it goes atm is very bad in production usage IMO.

However, I can't figure out the problem which produces error 050 and logs like those:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mpro.type' in 'field list'`
and a stracktrace like:
```
#0 /var/customers/webs/xxxxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php(377): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
#1 /var/customers/webs/xxxxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Base.php(774): Aimeos\MShop\Common\Manager\Base->getSearchResults(Object(Aimeos\MW\DB\Connection\DBAL), '\n\t\t\t\t\tSELECT mp...')
#2 /var/customers/webs/xxxxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Product/Manager/Standard.php(741): Aimeos\MShop\Common\Manager\Base->searchItemsBase(Object(Aimeos\MW\DB\Connection\DBAL), Object(Aimeos\MW\Criteria\SQL), 'mshop/product/m...', 'mshop/product/m...', Array, NULL, 3)
#3 /var/customers/webs/xxxxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Decorator/Depth.php(43): Aimeos\MShop\Product\Manager\Standard->searchItems(Object(Aimeos\MW\Criteria\SQL), Array, NULL)
#4 /var/customers/webs/xxxxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Index/Manager/DBBase.php(358): Aimeos\MShop\Common\Manager\Decorator\Depth->searchItems(Object(Aimeos\MW\Criteria\SQL), Array)
#5 /var/customers/webs/xxxxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Index/Manager/Standard.php(498): Aimeos\MShop\Index\Manager\DBBase->searchItemsIndexBase(Object(Aimeos\MW\Criteria\SQL), Array, 53, 'mshop/index/man...', 'mshop/index/man...')
#6 /var/customers/webs/xxxxx/vendor/aimeos/aimeos-core/lib/mshoplib/src/MShop/Common/Manager/Decorator/Depth.php(43): Aimeos\MShop\Index\Manager\Standard->searchItems(Object(Aimeos\MW\Criteria\SQL), Array, 53)
#7 /var/customers/webs/xxxxx/ext/ai-controller-frontend/controller/frontend/src/Controller/Frontend/Product/Standard.php(349): Aimeos\MShop\Common\Manager\Decorator\Depth->searchItems(Object(Aimeos\MW\Criteria\SQL), Array, 53)
#8 /var/customers/webs/xxxxx/ext/ai-client-html/client/html/src/Client/Html/Catalog/Base.php(618): Aimeos\Controller\Frontend\Product\Standard->searchItems(Object(Aimeos\MW\Criteria\SQL), Array, 53)
#9 /var/customers/webs/xxxxx/ext/ai-client-html/client/html/src/Client/Html/Catalog/Base.php(206): Aimeos\Client\Html\Catalog\Base->searchProducts(Object(Aimeos\MW\View\Standard))
#10 /var/customers/webs/xxxxx/ext/ai-client-html/client/html/src/Client/Html/Catalog/Lists/Standard.php(464): Aimeos\Client\Html\Catalog\Base->getProductList(Object(Aimeos\MW\View\Standard))
#11 /var/customers/webs/xxxxx/ext/ai-client-html/client/html/src/Client/Html/Catalog/Lists/Standard.php(171): Aimeos\Client\Html\Catalog\Lists\Standard->addData(Object(Aimeos\MW\View\Standard), Array, NULL)
#12 /var/customers/webs/xxxxx/htdocs/typo3conf/ext/aimeos/Classes/Controller/AbstractController.php(157): Aimeos\Client\Html\Catalog\Lists\Standard->getBody()
#13 /var/customers/webs/xxxxx/htdocs/typo3conf/ext/aimeos/Classes/Controller/CatalogController.php(70): Aimeos\Aimeos\Controller\AbstractController->getClientOutput(Object(Aimeos\Client\Html\Catalog\Lists\Standard))
#14 [internal function]: Aimeos\Aimeos\Controller\CatalogController->listAction()
#15 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(316): call_user_func_array(Array, Array)
#16 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(176): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->callActionMethod()
#17 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php(85): TYPO3\CMS\Extbase\Mvc\Controller\ActionController->processRequest(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response))
#18 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php(91): TYPO3\CMS\Extbase\Mvc\Dispatcher->dispatch(Object(TYPO3\CMS\Extbase\Mvc\Web\Request), Object(TYPO3\CMS\Extbase\Mvc\Web\Response))
#19 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/extbase/Classes/Core/Bootstrap.php(199): TYPO3\CMS\Extbase\Mvc\Web\FrontendRequestHandler->handleRequest()
#20 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/extbase/Classes/Core/Bootstrap.php(186): TYPO3\CMS\Extbase\Core\Bootstrap->handleRequest()
#21 [internal function]: TYPO3\CMS\Extbase\Core\Bootstrap->run('', Array)
#22 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(6341): call_user_func_array(Array, Array)
#23 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(41): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->callUserFunction('TYPO3\\CMS\\Extba...', Array, '')
#24 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(820): TYPO3\CMS\Frontend\ContentObject\UserContentObject->render(Array)
#25 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(736): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render(Object(TYPO3\CMS\Frontend\ContentObject\UserContentObject), Array)
#26 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(3538): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle('USER', Array)
#27 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(3500): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript_process(Array)
#28 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(3467): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()
#29 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/Http/RequestHandler.php(226): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->INTincScript()
#30 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/core/Classes/Core/Bootstrap.php(319): TYPO3\CMS\Frontend\Http\RequestHandler->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))
#31 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Classes/Http/Application.php(79): TYPO3\CMS\Core\Core\Bootstrap->handleRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))
#32 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Resources/Private/Php/frontend.php(23): TYPO3\CMS\Frontend\Http\Application->run()
#33 /var/customers/webs/xxxxx/vendor/typo3/cms/typo3/sysext/frontend/Resources/Private/Php/frontend.php(24): {closure}()
#34 /var/customers/webs/xxxxx/vendor/typo3/cms/index.php(3): require('/var/customers/...')
#35 {main}
```

Can you please help my track this down?

**Comment by aimeos** [comment]
Please don't update your existing 18.x version because the new 19.1 is major release is beta with a lot of breaking changes: https://aimeos.org/docs/Developers/Changelog

We use semantic versioning (https://en.wikipedia.org/wiki/Software_versioning) with a beta release xx.1.z and stable releases xx.4.z, xx.7.z and xx.10.z LTS. Bugfix releases are e.g. 18.10.1 to 18.10.z. Most breaking changes are due to removing code which has been marked with @deprecated. Some changes are also not possible with maininging backward compatibility. Therefore, the first release every year (19.1 now) contains all major breaking changes which will stabilize until the release in April (19.4).

To anwser your last question: You have to run the setup tasks in the Extension Manager or from the command line with `typo3_console aimeos:setup`

**Comment by aimeos** [comment]
Yes, maintaining the createController() method would be possible if we hadn't renamed the protected method that's actually createing the object to createController() either.

**Comment by aimeos** [comment]
Here are the support periods described and the tasks on our roadmap:
https://aimeos.org/project/roadmap/
