### ISSUE TITLE
 A non-recoverable error occured f_sort=name

### ISSUE THREAD

**Issue by MahmoudDevo** [aimeos/aimeos-core#228]
Hi;
PostgreSQL 9.6.15
Laravel Framework 8.37.0
PHP 7.4.16
"php": "^7.3|^8.0",
"aimeos/aimeos-laravel": "~2021.04",

when i try to search by name like: 
**http://127.0.0.1:8000/en/shop?f_sort=name**
`A non-recoverable error occured`
in the log: 
`Missing required parameter for [Route: aimeos_shop_detail] [URI: {locale}/shop/{d_name}/{d_pos?}/{d_prodid?}] [Missing parameter: d_name].`

Thank you

**Comment by aimeos** [comment]
Did you change the catalog/lists template? Can you post a screenshot with the line in the template where it occurs?

**Comment by MahmoudDevo** [comment]
Hi,
More information.
```
#0 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\RouteUrlGenerator.php(91): Illuminate\Routing\Exceptions\UrlGenerationException::forMissingParameters(Object(Illuminate\Routing\Route), Array)
#1 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(451): Illuminate\Routing\RouteUrlGenerator->to(Object(Illuminate\Routing\Route), Array, false)
#2 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\UrlGenerator.php(426): Illuminate\Routing\UrlGenerator->toRoute(Object(Illuminate\Routing\Route), Array, false)
#3 C:\laragon\www\devoshop_v8.7\ext\ai-laravel\lib\custom\src\MW\View\Helper\Url\Laravel5.php(61): Illuminate\Routing\UrlGenerator->route('aimeos_shop_det...', Array, false)
#4 [internal function]: Aimeos\MW\View\Helper\Url\Laravel5->transform('aimeos_shop_det...', 'catalog', 'detail', Array, Array, Array)
#5 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Standard.php(88): call_user_func_array(Array, Array)
#6 C:\laragon\www\devoshop_v8.7\ext\devoext\client\html\templates\common\partials\products-standard.php(142): Aimeos\MW\View\Standard->__call('url', Array)
#7 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Standard.php(282): include('C:\\laragon\\www\\...')
#8 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Standard.php(264): Aimeos\MW\View\Standard->includeFile('C:\\laragon\\www\\...')
#9 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Helper\Partial\Standard.php(36): Aimeos\MW\View\Standard->render('common/partials...')
#10 [internal function]: Aimeos\MW\View\Helper\Partial\Standard->transform('common/partials...', Array)
#11 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Standard.php(88): call_user_func_array(Array, Array)
#12 C:\laragon\www\devoshop_v8.7\ext\devoext\client\html\templates\catalog\lists\items-body-standard.php(60): Aimeos\MW\View\Standard->__call('partial', Array)
#13 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Standard.php(282): include('C:\\laragon\\www\\...')
#14 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-core\lib\mwlib\src\MW\View\Standard.php(264): Aimeos\MW\View\Standard->includeFile('C:\\laragon\\www\\...')
#15 C:\laragon\www\devoshop_v8.7\ext\devoext\client\html\src\Client\Html\Catalog\Lists\Items\Devostandard.php(116): Aimeos\MW\View\Standard->render('catalog/lists/i...')
#16 C:\laragon\www\devoshop_v8.7\ext\ai-client-html\client\html\src\Client\Html\Catalog\Lists\Standard.php(180): Aimeos\Client\Html\Catalog\Lists\Items\Devostandard->getBody('')
#17 C:\laragon\www\devoshop_v8.7\ext\ai-client-html\client\html\src\Client\Html\Common\Decorator\Base.php(104): Aimeos\Client\Html\Catalog\Lists\Standard->getBody('')
#18 C:\laragon\www\devoshop_v8.7\vendor\aimeos\aimeos-laravel\src\Aimeos\Shop\Controller\CatalogController.php(91): Aimeos\Client\Html\Common\Decorator\Base->getBody()
#19 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Aimeos\Shop\Controller\CatalogController->listAction('ar')
#20 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('listAction', Array)
#21 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Route.php(254): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Aimeos\Shop\Controller\CatalogController), 'listAction')
#22 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Route.php(197): Illuminate\Routing\Route->runController()
#23 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Router.php(695): Illuminate\Routing\Route->run()
#24 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Session\Middleware\AuthenticateSession.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\AuthenticateSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#35 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Router.php(697): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Router.php(672): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#44 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#45 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#46 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#47 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 C:\laragon\www\devoshop_v8.7\vendor\fruitcake\laravel-cors\src\HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\laragon\www\devoshop_v8.7\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 C:\laragon\www\devoshop_v8.7\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 C:\laragon\www\devoshop_v8.7\public\index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 C:\laragon\www\devoshop_v8.7\server.php(21): require_once('C:\\laragon\\www\\...')
#66 {main}
```

**Comment by aimeos** [comment]
There's an error in your template and you don't pass the required parameters to the method generating the URL.

**Comment by MahmoudDevo** [comment]
Hi,
This because label of product is empty.
Thank you
