### ISSUE TITLE
Upgrade script ProductRenameStockWarehouse fails on update from 16_4_3 to 17_4.

### ISSUE THREAD

**Issue by faerietree** [aimeos/aimeos-core#90]
```
Changing warehouseid column in mshop_product_stock                    OK
Adding label and status columns for product warehouse                 
Rename warehouse table                                                
  Drop "mshop_product_stock.fk_msprost_whid"                          OK
  Rename "mshop_product_stock.wareshouseid"                           
Executing statement "ALTER TABLE "mshop_product_stock" CHANGE COLUMN "warehouseid" "typeid" INTEGER NOT NULL" failed: An exception occurred while executing 'ALTER TABLE "mshop_product_stock" CHANGE COLUMN "warehouseid" "typeid" INTEGER NOT NULL':

SQLSTATE[HY000]: General error: 1025 Error on rename of './hamag0/#sql-2ad3_50ed' to './hamag0/mshop_product_stock' (errno: 150)
#0 /var/www/hamag/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Task/Base.php(126): Aimeos\MW\DB\Statement\DBAL\Simple->execute()
#1 /var/www/hamag/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mshoplib/setup/ProductRenameStockWarehouse.php(84): Aimeos\MW\Setup\Task\Base->execute('ALTER TABLE "ms...', 'db-product')
#2 /var/www/hamag/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(204): Aimeos\MW\Setup\Task\ProductRenameStockWarehouse->migrate()
#3 /var/www/hamag/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(198): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array, Array)
#4 /var/www/hamag/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(198): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array, Array)
#5 /var/www/hamag/typo3conf/ext/aimeos/Resources/Libraries/aimeos/aimeos-core/lib/mwlib/src/MW/Setup/Manager/Multiple.php(112): Aimeos\MW\Setup\Manager\Multiple->migrateTasks(Array)
#6 /var/www/hamag/typo3conf/ext/aimeos/Classes/Setup.php(76): Aimeos\MW\Setup\Manager\Multiple->migrate()
#7 /var/www/hamag/typo3temp/ExtensionManager/UpdateScripts/ext_update9db0a92204a53e69894c4bc712cd3591.php(47): Aimeos\Aimeos\Setup::execute()
#8 /var/www/typo3_src-7.6.10/typo3/sysext/extensionmanager/Classes/Utility
```

**Comment by faerietree** [comment]
Common cause is if there are still foreign keys referencing the column to be renamed. I checked for foreign keys but none were found.
I used:
```
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, CONSTRAINT_, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM KEY_COLUMN_USAGE WHERE REFERENCED_TABLE_SCHEMA = 'hamag0' AND REFERENCED_TABLE_NAME = 'mshop_product_stock';
CONSTRAINT_CATALOG  CONSTRAINT_SCHEMA   
CONSTRAINT_NAME     CONSTRAINT_TYPE     
mysql> SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM KEY_COLUMN_USAGE WHERE REFERENCED_TABLE_SCHEMA = 'hamag0' AND REFERENCED_TABLE_NAME = 'mshop_product_stock';
```

Next - the database will be restored and a step by step update executed, i.e. not skipping any versions.

**Comment by faerietree** [comment]
May also be due to a misorder of upgrade script execution? Are the scripts executed alphabetically? Anyway, using #91 both cases (`stock_warehouseid`, `_whid`) should be covered.
```
lib/mshoplib/setup/ProductRenameStockWarehouse.php:             'constraint1' => 'ALTER TABLE "mshop_product_stock" DROP FOREIGN KEY "fk_msprost_stock_warehouseid"',
lib/mshoplib/setup/ProductRenameStockWarehouse.php:                     else if ( $schema->constraintExists( 'mshop_product_stock', 'fk_msprost_stock_warehouseid' )
lib/mshoplib/setup/ProductChangeStockWarehouseIdNotNull.php:                    DROP FOREIGN KEY "fk_msprost_stock_warehouseid",
lib/mshoplib/setup/ProductChangeStockWarehouseIdNotNull.php:                    ADD CONSTRAINT "fk_msprost_stock_warehouseid"
lib/mshoplib/setup/ProductRenameStockWarehouse.php:             'constraint1' => 'ALTER TABLE "mshop_product_stock" DROP FOREIGN KEY "fk_msprost_stock_warehouseid"',
lib/mshoplib/setup/ProductRenameStockWarehouse.php:                     else if ( $schema->constraintExists( 'mshop_product_stock', 'fk_msprost_stock_warehouseid' )
lib/mshoplib/setup/ProductChangeStockWarehouseIdNotNull.php:                    DROP FOREIGN KEY "fk_msprost_stock_warehouseid",
lib/mshoplib/setup/ProductChangeStockWarehouseIdNotNull.php:                    ADD CONSTRAINT "fk_msprost_stock_warehouseid"
```

**Comment by aimeos** [comment]
The setup tasks are ordered according to the pre- and post-dependencies defined in the setup task classes. Maybe the order of the tasks is incorrect like you've stated.
